backend:
  name: github
  repo: HAMMOU2310/AllAffiliate_Store
  branch: main
  client_id: "0f443b6966c6f7c1277eafbb68fe51d94cfcb8eb"
  pkce: true

media_folder: "images/uploads" # مجلد حفظ صور المنتجات
public_folder: "/images/uploads"

collections:
  - name: "store_data"
    label: "إدارة المتجر"
    delete: false
    editor:
      preview: false
    files:
      - file: "data/products.json"
        label: "قائمة المنتجات النشطة"
        name: "products_list"
        fields:
          - name: "products"
            label: "المنتجات"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - {label: "عنوان جذاب للمنتج", name: "title", widget: "string"}
              - {label: "الوصف المقنع (Pinterest Friendly)", name: "description", widget: "text"}
              - {label: "رابط الأفلييت المشفر الخاص بك", name: "affiliate_link", widget: "string"}
              - {label: "صورة المنتج العالية الجودة", name: "image", widget: "image"}
              - {label: "تاريخ النشر", name: "date", widget: "datetime"}